type Person {
  id: String!
  name: String!
  children: [Person]
  score: Int!
}
type Query {
  getPerson(id: String!): Person
}
input PersonInput {
  name: String!
}
type Mutation {
  deletePerson(id: ID!): Person
  addPerson(input: PersonInput!): Person
  updateName(id: ID!, name: String!): Person
}
