name: build
on:
  pull_request: {}
  workflow_call: {}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      CLEAN_UP_STACK: "1"
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build

  test:
    needs: [build]
    concurrency: pr-test-${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      CI: "true"
      CLEAN_UP_STACK: "1"
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::593491530938:role/githubActionStack-githubactionroleA106E4DC-14SHKLVA61IN4
          aws-region: us-east-1
          role-duration-seconds: 3600
        if: contains(fromJson('["release", "build", "close"]'), github.workflow)

      - name: Run tests
        run: yarn turbo run test
        env:
          TEST_DEPLOY_TARGET: AWS
          NODE_OPTIONS: --max-old-space-size=6144
