name: build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      CI: "true"
      CLEAN_UP_STACK: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo-cache
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::593491530938:role/githubActionStack-githubactionroleA106E4DC-14SHKLVA61IN4
          aws-region: us-east-1
          role-duration-seconds: 3600
        if: contains(fromJson('["release", "build", "close"]'), github.workflow)

      - name: Install dependencies
        run: yarn install --check-files

      - name: Build Packages
        run: yarn turbo run build -- --cache-dir=.turbo-cache
        env:
          NODE_OPTIONS: --max-old-space-size=6144

      - name: Run tests
        run: yarn turbo run test -- --cache-dir=.turbo-cache
        env:
          TEST_DEPLOY_TARGET: AWS
          NODE_OPTIONS: --max-old-space-size=6144
