name: release
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      CI: "true"
      TEST_STACK_RETENTION_POLICY: DELETE
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build

      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: release
        run: yarn lerna publish --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
