name: release
on:
  push:
    branches:
      - canary
  workflow_dispatch: {}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      CI: "true"
      TEST_STACK_RETENTION_POLICY: DELETE
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set git identity
        run: |-
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::593491530938:role/githubActionStack-githubactionroleA106E4DC-14SHKLVA61IN4
          aws-region: us-east-1
          role-duration-seconds: 3600
        if: contains(fromJson('["release", "build", "close"]'), github.workflow)
      - name: Install dependencies
        run: yarn install --check-files --frozen-lockfile
      - name: release
        run: yarn lerna publish from-package --loglevel silly --dist-tag canary --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Archive lerna logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lerna-logs
          path: lerna-debug.log
